Inline method that was called in the Decimal constructor
There appears to be an mcs bug that results in "error CS0188: The `this' object cannot be used before all of its fields are assigned to"
for the SetBits() method call despite all the fields being initialized directly above.

Copying the SetBits() method directly into the constructor works around this and seems to be what Miguel did in the Mono referencesource fork:
https://github.com/mono/referencesource/commit/9c6e5e2ee332d23c8d07e311c234337205d22642